spring:
  application:
    name: gateway-server
  profiles:
    active: "dev"
#  config:
#    import: ${SPRING_CLOUD_CONFIG_URI}
#  cloud:
#    config:
#      name: gateway-server
#      profile: dev
